Replace base with osl-resources
osuosl-cookbooks/osl-ceph pull request #33
Opened 2021-09-23 21:21 UTC by TheREK3R

2021-09-27 21:08 UTC, ramereth requested changes

2021-09-27 21:08 UTC, ramereth commented on Berksfile
> -cookbook 'base', git: 'git@github.com:osuosl-cookbooks/base'
This needs to stay due to dependencies in the other cookbooks.

2022-08-23 15:20 UTC, ramereth commented
!bump minor ~

2022-08-23 15:20 UTC, merged

2022-08-23 15:20 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v4.6.0.  Have a nice day!