Test Kitchen Config Refactor
osuosl-cookbooks/osl-ceph pull request #54
Opened 2024-10-16 23:05 UTC by zwall-bp

All tests green, except for dokken suffering from issues in:
* mon
* mgr
* mds
* osd

Anything that utilizes `mon` has issues with spinning up the instance. Logs only provide:
```
Oct 16 22:58:49 node1 ceph-mds[15264]: 2024-10-16 22:58:49.297 7f75f0a70700  1 mds.node1 Updating MDS map to version 265 from mon.0
Oct 16 22:58:52 node1 ceph-mds[15264]: 2024-10-16 22:58:52.589 7f75f0a70700  1 mds.node1 Updating MDS map to version 266 from mon.0
Oct 16 22:58:57 node1 ceph-mds[15264]: 2024-10-16 22:58:57.070 7f75f0a70700  1 mds.node1 Updating MDS map to version 267 from mon.0
Oct 16 22:59:01 node1 ceph-mds[15264]: 2024-10-16 22:59:01.470 7f75f0a70700  1 mds.node1 Updating MDS map to version 268 from mon.0
Oct 16 22:59:09 node1 ceph-mds[15264]: 2024-10-16 22:59:09.530 7f75f0a70700  1 mds.node1 Updating MDS map to version 269 from mon.0
Oct 16 22:59:12 node1 ceph-mds[15264]: 2024-10-16 22:59:12.950 7f75f0a70700  1 mds.node1 Updating MDS map to version 270 from mon.0

```

2024-10-18 23:25 UTC, ramereth requested changes

2024-10-18 23:25 UTC, ramereth commented on resources/mon.rb
> +
Please use the [sysctl resource](https://docs.chef.io/resources/sysctl/) instead.

2024-10-22 22:18 UTC, ramereth commented
@zwall-bp I'm having a lot of trouble with dokken due to the use of lvm. My workstation also uses lvm and so it gets mixed up with the system lvm.

Let's just remove dokken support from this cookbook.

2024-10-22 23:14 UTC, zwall-bp commented
10-4

2024-10-23 19:19 UTC, ramereth commented
!bump patch ~

2024-10-23 19:19 UTC, merged

2024-10-23 19:20 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v6.5.3.  Have a nice day!